### ISSUE TITLE
@ApiResponses does not generate a "responses:" section in the swagger 2.0 api-docs

### ISSUE THREAD

**Issue by mrwanny** [springdox/springdox#608]
I cannot figure out why @ApiResponses does not generate a "responses:" section in the swagger 2.0 api-docs
for example if I annotate a  method with 
@ApiOperation(value = "adds 2 numbers",httpMethod = "GET",response = String.class)
@ApiResponses(value = {@ApiResponse(code = 200, message = "sum", response = Result.class)})
public Result add(@ApiParam(value = "a", required = true, defaultValue = "0")   @RequestParam("a")Double a, @ApiParam(value = "b", required = true, defaultValue = "0") @RequestParam("b" )Double b) {
		Result res = new Result();
		res.setResult(a+b);
		return res;
	}
where Result looks like
@ApiModel(description = "result of an Operation")
public class Result {
    @ApiModelProperty(required = true)
    @JsonProperty("result")
    public Double getResult() {
        return result;
    }
   ...
 the api-docs does not contain the "responses": section
"paths": {
    "/calculator/add": {
      "get": {
        "summary": "adds 2 numbers",
        "parameters": [
          {
            "name": "a", "in": "query",  "description": "a", "required": true, "type": "number","default": "0","format": "double"
          },
          {
            "name": "b", "in": "query", "description": "b","required": true,"type": "number", "default": "0","format": "double"
          }
        ]
      }
    },

**Comment by dilipkrish** [comment]
@mrwanny this is the wrong branch... you should look at this branch [refactor/538/spike-to-seperate-models-and-dtos](https://github.com/martypitt/swagger-springmvc/tree/refactor/538/spike-to-seperate-models-and-dtos). Its almost feature complete.

**Comment by mrwanny** [comment]
@dilipkrish I understand, I will checkout out refactor/538/... thanks for the hint

**Comment by mrwanny** [comment]
@dilipkrish I checkout out  refactor/538/spike-to-seperate-models-and-dtos and I am trying to migrate to the new api... unfortunately I am having some issue following the readme...
instead of 
compile "com.mangofactory:swagger-springmvc:2.0.0-SNAPSHOT"
I tried to put 
compile "com.mangofactory.documentation:mangodocs-swagger:2.0.0-SNAPSHOT"
compile "com.mangofactory.documentation:mangodocs-spring-web:2.0.0-SNAPSHOT"
compile "com.mangofactory.documentation:mangodocs-swagger-common:2.0.0-SNAPSHOT"
compile "com.mangofactory.documentation:mangodocs-swagger2:2.0.0-SNAPSHOT"
but I things like
com.mangofactory.documentation.spi
are still missing...
Do you have any suggestion on how to get the new apis up and running?
Thanks for the help

**Comment by dilipkrish** [comment]
@mrwanny sorry its all still work in progress! :open_mouth:  Thanks for taking time to take an early peek at whats coming down the pipe.

We were going to update the readme once we migrate the demo application. But I wasn't going to do that until we were feature complete. Also keep in mind these haven't been released as SNAPSHOTS yet. 

Also keep in mind the package names **will most likely change** as we're planning to move to a separate github organization.

Anywho, 
Depending on which version you want to use, you'd need to pick between one of ```mangodocs-swagger``` or ```mangodocs-swagger2```

Lets say you're going to play with swagger 2 then these should be what you need. Some of them would be pulled in transitively, so I'm not sure, are you publishing the artifacts to you maven local repository? Anyway, these should get you what you need.

```gradle
compile "com.mangofactory.documentation:mangodocs-core:2.0.0-SNAPSHOT"
compile "com.mangofactory.documentation:mangodocs-spi:2.0.0-SNAPSHOT"
compile "com.mangofactory.documentation:mangodocs-schema:2.0.0-SNAPSHOT"
compile "com.mangofactory.documentation:mangodocs-spring-web:2.0.0-SNAPSHOT"
compile "com.mangofactory.documentation:mangodocs-swagger-common:2.0.0-SNAPSHOT"
compile "com.mangofactory.documentation:mangodocs-swagger2:2.0.0-SNAPSHOT"
```

**Comment by mrwanny** [comment]
@dilipkrish Thanks a lot for the explanation, of course I understand that this is still under development and I would love to help if I can.

Yes I am publishing artifacts to my local maven repo  
````./gradlew publishToMavenLocal``` 
from what I can see core,spi,schema are not being pulled transitively, I experimented with adding the publish task to their respective build.gradle and all 6 artifacts got published.
(https://github.com/mrwanny/swagger-springmvc/commit/d543196d4717c3a0d163f8db71a04bf1bdcfbc8b)

...in my @EnableSwagger2 class I tried to replaced the SwaggerSpringMvcPlugin @Bean with a
@Bean
   public DocumentationConfigurer customImplementation(){
      return new DocumentationConfigurer(DocumentationType.SWAGGER_2).groupName("plugin").includePatterns(".*calculator.*");
   }```

but I think I am still missing something since I get an exception about a missing bean for 
```com.mangofactory.documentation.spi.service.ResourceGroupingStrategy```

Thanks again for the help

**Comment by dilipkrish** [comment]
@mrwanny do you have a repo you can share?

**Comment by mrwanny** [comment]
Yes, https://github.com/mrwanny/swagger2-rest

**Comment by dilipkrish** [comment]
@mrwanny I pushed an update to the build scripts and also fixed a bean configuration bug. Now it looks like it starts up but there is an NPE issue on repo with ```DocumentationPluginsBootstrapper```. 

The thing is when swagger 1.2 is enabled, the object mapper is set, but when only swagger 2 is enabled it does not get set.

Working on it!

**Comment by dilipkrish** [comment]
@mrwanny I fixed the what the application is loaded. Take a look and see if it fixes your issue.

**Comment by mrwanny** [comment]
Yes, It works nicely now! Thanks a lot for the help
