### ISSUE TITLE
Java codegen - generates class name Void.java

### ISSUE THREAD

**Issue by rajeshkamal** [springdox/springdox#617]
Spring REST controller returns void for DELETE operation.
    
    @ApiOperation(value = "Delete a contact")
    @RequestMapping(value = "/contact/{contactId}", method = RequestMethod.DELETE)
    @ResponseStatus(value = HttpStatus.NO_CONTENT)
    public @ResponseBody void delete(@PathVariable String contactId) {
        contactService.delete(contactId);
    }

Using swagger springmvc for generating the swagger spec 1.2.

The spec contains a Void model for some reason and inturn generates a Void.java. How can we avoid this.
{
    "apiVersion": "1.0",
    "swaggerVersion": "1.2",
    "basePath": "/",
    "resourcePath": "/contact",
    "produces": [
        "*/*"
    ],
    "consumes": [
        "application/json"
    ],
    "apis": [
        {
            "path": "/contact/{contactId}",
            "description": "delete",
            "operations": [
                {
                    "method": "DELETE",
                    "summary": "Delete a contact",
                    "notes": "delete",
                    "nickname": "delete",
                    "produces": [
                        "*/*"
                    ],
                    "consumes": [
                        "application/json"
                    ],
                    "parameters": [
                        {
                            "allowMultiple": false,
                            "defaultValue": "",
                            "description": "contactId",
                            "name": "contactId",
                            "paramType": "path",
                            "type": "string",
                            "required": true
                        }
                    ],
                    "responseMessages": [
                        {
                            "code": 204,
                            "message": "No Content"
                        },
                        {
                            "code": 401,
                            "message": "Unauthorized"
                        },
                        {
                            "code": 403,
                            "message": "Forbidden"
                        }
                    ],
                    "deprecated": "false",
                    "type": "void"
                }
            ]
        }
    ],
    "models": {
        "Void": {
            "description": "",
            "id": "Void",
            "properties": {}
        }
    }
}

**Comment by dilipkrish** [comment]
@rajeshkamal This is a bug in 1.0.0 however its fixed in the 2.0 work we've been doing

**Comment by dilipkrish** [comment]
Closing this issue as its been fixed in 2.0

**Comment by rajeshkamal** [comment]
Thanks @dilipkrish . Can you let me know on how to get the fix for this. ? branch ?

Also I have a doubt, the current swagger-springmvc integration produces spec 1.2. So the new 2.0 milestone which you were referring to will also produce the same 1.2 spec or 2.0.

If it is 2.0 then, how much will it affect the code generation. Is the generated code from a 1.2 spec is backward compatible with the 2.0 spec. ?

**Comment by rkaltreider** [comment]
@dilipkrish I am also suffering from this issue and anxiously awaiting 2.0.0.  Any idea when we will be able to get access to the 2.0.0 version? Also, are there any workarounds in the time being?

**Comment by dilipkrish** [comment]
@rkaltreider/ @rajeshkamal I'll push out a build of 1.0.2 with this and a couple of other fixes some time today. This is most likely the last patch release in the 1.x version. Over the weekend we'll probably bring 2.0.x branch to master /c @adrianbk

**Comment by rkaltreider** [comment]
@dilipkrish looking forward to it.  For the time being I updated all of my controller methods to return an object.  Currently all road blocks are cleared, so please don't feel rushed.  Thanks again!

**Comment by dilipkrish** [comment]
@rkaltreider 1.0.2 is pushed to sonatype, so it should be a few hours before it propogates. Rather than change the operations to return object, add the ```Void.class``` and ```Void.TYPE``` to the ignorables. see the [commit](https://github.com/springfox/springfox/commit/6c44c6faea6b35611d0c3841ca106243682b3080) above.
