### ISSUE TITLE
Java codegen - generates class name Collection<Model>.java

### ISSUE THREAD

**Issue by rajeshkamal** [springdox/springdox#620]
Using the swagger springmvc to generate the swagger spec from a Spring REST impementation. 
The Spring REST controller class returns a Collection<Model> Ex:

    @ApiOperation(value = "List all contacts")
    @RequestMapping(value = "/contacts", method = RequestMethod.GET)
    @ResponseStatus(value = HttpStatus.OK)
    public Collection<Contact> list() {
        return contactService.list();
    }

Running the swagger codegen onto the generated swagger spec which is 2.0. Used latest 2.0 @springdox development branch bits.

Returning a List<Model> seems to work fine. But returning a Collection<Model> generates a class like this - CollectionÂ«BundleÂ».java

Am I missing something here.? Kindly share your inputs on this.

**Comment by dilipkrish** [comment]
@rajeshkamal you need to follow [these instructions](https://github.com/springdox/springdox/issues/526#issuecomment-83632352) to generate the right models. Closing this issue, since I think its duplicate. Feel free to reopen if it doesn't fix your problem
